name: Upload assets to Smooth Bundle

on:
  push:
    branches: [main]

jobs:
  upload-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install Smooth Bundle CLI
        run: yarn global add @smoothbundle/cli

      - name: Install dependencies
        run: yarn

      - name: Build assets
        run: yarn build

      - name: Upload assets to Smooth Bundle
        env:
          SBUNDLE_TOKEN: ${{ secrets.SCDN_TOKEN }}
        run: |
          sbundle create-version
          sbundle push
          sbundle publish-version
