name: Upload assets to Smooth CDN

on:
  push:
    branches: [main]

jobs:
  upload-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Smooth CDN CLI
        run: yarn global add @smoothcdn/cli

      - name: Install dependencies
        run: yarn

      - name: Build assets
        run: yarn build

      - name: Upload assets to Smooth CDN
        env:
          SCDN_TOKEN: ${{ secrets.SCDN_TOKEN }}
        run: |
          scdn create-version
          scdn push
          scdn publish-version
